name: test-workflows
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: REPO_NAME=$(echo ${{ github.repository }})
      - run: echo "github：${{ github.ref }}"
      - run: echo "env输出：${{ env.REPO_NAME }}"
      - run: echo "输出secrets：${{ secrets.TEST_PASSWORD }}"
#       - run: echo "输出envTEST_USERNAME：：：$GITHUB_REF"
#         if:  ${{secrets.TEST_PASSWORD}} == '123'
      - run: echo "vars：${{ vars.TEST_VAR }}"
     
     
