name: test-workflows
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "github：${{ github.ref }}"
#       - run: echo "env：${{ env. }}"
      - run: echo "输出secrets：${{ secrets.TEST_PASSWORD }}"
#         if:  ${{secrets.TEST_PASSWORD}} == '123'
      - run: echo "123123：${{ vars.TEST_VAR }}"
     
